const CONFIG = {
    MODRINTH_API: 'https://api.modrinth.com/v2',
    SPIGET_API: 'https://api.spiget.org/v2',
    HANGAR_API: 'https://hangar.papermc.io/api/v1',
    DEFAULT_LOCALE: 'zh-CN',
    
    // 类别映射扩展
    CATEGORIES: [
        {
            id: 'all',
            nameKey: 'category.all',
            name: '全部',
            icon: 'fa-border-all',
            modrinth: null,
            spigot: null,
            hangar: null
        },
        { 
            id: 'admin', 
            nameKey: 'category.admin',
            name: '管理工具', 
            icon: 'fa-shield-halved', 
            modrinth: 'management', 
            spigot: 25,
            hangar: 'ADMIN_TOOLS'
        },
        { 
            id: 'gameplay', 
            nameKey: 'category.gameplay',
            name: '游戏机制', 
            icon: 'fa-bolt', 
            modrinth: 'game-mechanics',
            spigot: 22,
            hangar: 'GAMEPLAY'
        },
        { 
            id: 'world', 
            nameKey: 'category.world',
            name: '世界生成', 
            icon: 'fa-globe', 
            modrinth: 'worldgen', 
            spigot: 24,
            hangar: 'WORLD_MANAGEMENT'
        },
        { 
            id: 'economy', 
            nameKey: 'category.economy',
            name: '经济系统', 
            icon: 'fa-coins', 
            modrinth: 'economy', 
            spigot: 21,
            hangar: 'ECONOMY'
        },
        { 
            id: 'chat', 
            nameKey: 'category.chat',
            name: '聊天社交', 
            icon: 'fa-comments', 
            modrinth: 'social', 
            spigot: 19,
            hangar: 'CHAT'
        },
        { 
            id: 'utility', 
            nameKey: 'category.utility',
            name: '实用工具', 
            icon: 'fa-wrench', 
            modrinth: 'utility', 
            spigot: 20,
            hangar: 'MISC'
        },
        { 
            id: 'protection', 
            nameKey: 'category.protection',
            name: '保护系统', 
            icon: 'fa-shield', 
            modrinth: 'management', 
            spigot: 23,
            hangar: 'PROTECTION'
        },
        { 
            id: 'minigames', 
            nameKey: 'category.devtools',
            name: '库/API', 
            icon: 'fa-code', 
            modrinth: 'library', 
            spigot: 26,
            hangar: 'DEV_TOOLS'
        },
    ],

    TAG_TRANSLATIONS: {
        'zh-CN': {
            'management': '管理',
            'game-mechanics': '游戏机制',
            'worldgen': '世界',
            'economy': '经济',
            'social': '社交',
            'utility': '实用工具',
            'protection': '保护系统',
            'library': '库',
            'plugin': '插件',
            'admin_tools': '管理工具',
            'chat': '聊天',
            'dev_tools': '开发工具',
            'economy': '经济',
            'gameplay': '游戏机制',
            'games': '游戏',
            'protection': '保护',
            'role_playing': '角色扮演',
            'world_management': '世界生成',
            'misc': '其他',
            'undefined': '未分类',
            'storage': '存储',
            'cursed': '怪诞',
            'transportation': '交通',
            'technology': '科技',
            'adventure': '冒险',
            'magic': '魔法',
            'mobs': '生物',
            'food': '食物',
            'minigame': '小游戏',
            'optimization': '优化',
            'equipment': '装备',
            'decoration': '装饰'
        },
        en: {
            'management': 'Management',
            'game-mechanics': 'Game Mechanics',
            'worldgen': 'Worldgen',
            'economy': 'Economy',
            'social': 'Social',
            'utility': 'Utility',
            'protection': 'Protection',
            'library': 'Library',
            'plugin': 'Plugin',
            'admin_tools': 'Admin Tools',
            'chat': 'Chat',
            'dev_tools': 'Dev Tools',
            'gameplay': 'Gameplay',
            'games': 'Games',
            'role_playing': 'Role Playing',
            'world_management': 'World Management',
            'misc': 'Misc',
            'undefined': 'Uncategorized',
            'storage': 'Storage',
            'cursed': 'Cursed',
            'transportation': 'Transportation',
            'technology': 'Technology',
            'adventure': 'Adventure',
            'magic': 'Magic',
            'mobs': 'Mobs',
            'food': 'Food',
            'minigame': 'Minigame',
            'optimization': 'Optimization',
            'equipment': 'Equipment',
            'decoration': 'Decoration'
        }
    }
};
